package exception;

public class ExceptionExam {
	
	public void runtimeE(){
		String [] ary = {"A","B","C","D"};
		try{
			for(int i =0;i<=ary.length;i++){
				System.out.println(ary[i]);
				//여기서예외발견확인
		
			}
		}catch(Exception e){
			e.printStackTrace();
		}finally{
			System.out.println("예외발생상관 없이수행");
		}
	}
	
	
}
